### ISSUE TITLE
Error when running docker command

### ISSUE THREAD

**Issue by bhjakobsen** [Leapsight/bondy#9]
===> BONDY_TMP_DIR=./tmp
===> [info] validate-config Validating configuration files
escript: exception error: bad argument
  in function  io:format/2
     called as io:format("~s===> [info] validate-config No Bondy configuration file found at ~p. Bondy will use the default configuration. Otherwise please make sure a 'bondy.conf' file (or 'bondy.conf.template' in case environment variables replacement is required) is present in the ~p directory.~s~n",
                         ["\e[0m","./etc","\e[0m"])
     *** argument 1: wrong number of arguments

**Comment by aramallo** [comment]
@bhjakobsen I fixed the above error (a log format error) on the `develop` branch, thanks!  The reason why you hit this one is because you either not providing a `bondy.conf` or `bondy.conf.template` file (the latter to be used when you need environment variable replacement in your config file) or the path you are mounting is incorrect.

The fix will be included in the `develop` docker image as soon as the CI finishes.

I will close this issue, but please do not hesitate in opening a new one in case you find another problem.
